### ISSUE TITLE
Make more configuration environment dependent

### ISSUE THREAD

**Issue by epaune-k** [am-kantox/kantox-herro#2]
Now formatters can be set differently by environment, by I would like to see more environment-dependent settings. Stopwords, for instance, and spitters

**Comment by am-kantox** [comment]
Underlying [config library](https://github.com/am-kantox/) changed to gracefully lookup `blah.foo.bar.baz` in `foo.bar.baz` if the specific value was not found.

Usage:

```
foo:
  bar: 42
  baz: 3.14
production:
  foo:
    baz: 2.71
```

Request to `production.foo.baz` returns `2.71`, request to `production.foo.bar` returns `42`.
